name: kddcup
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7.6
  - tensorflow=1.15.0
  - flask=1.1.1
  - keras=2.3.1
  - lightgbm=2.3.0
  - pandas=1.0.2
  - psutil=5.7.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - theano=1.0.4
  - pytorch=1.4.0
  - torchvision=0.5.0
  - pyyaml=5.3.1

